[package]
name = "proxy-subscriber"
version = "0.1.0"
edition = "2021"

[dependencies]
axum="0.4"
tokio={version="1", features=["full"]}
askama = "0.11"
tower-http = { version = "0.2", features = ["fs"] }
